### ISSUE TITLE
How to support source_relative option？

### ISSUE THREAD

**Issue by zhb127** [chrusty/protoc-gen-jsonschema#151]
Looking at the source code, I did not find source_relative related option.

```
./proto/
  - v1/
    - demo1_params.proto
  - v2/
    - demo2_params.proto
```

use buf remote plugin:

```
- plugin: buf.build/community/chrusty-jsonschema:v1.4.1
    out: ./api
    opt:
      - paths=source_relative
```

just output file:

```
./api/
- Demo1Params.json
- Demo2Params.json
```
